version: '3.8'

services:
  postgres:
    image: postgres:latest  
    container_name: flask-db
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: recipe_dev 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432" 

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000" 
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/recipe_dev  
    command: >
      bash -c "flask db upgrade && flask run --host=0.0.0.0"
    depends_on:
      - postgres 

volumes:
  postgres_data:
