"""Added recipe_categories table and relation in recipe

Revision ID: 5784dceadbab
Revises: bd33f8f7e443
Create Date: 2025-05-01 11:53:16.813855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5784dceadbab'
down_revision = 'bd33f8f7e443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'recipe_categories', ['category_id'], ['category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('recipe_categories')
    # ### end Alembic commands ###
